<a href="https://colab.research.google.com/github/PrabuddaKumara/Library_System/blob/main/tenserflo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# In this notebook,we're going to cover some of the most fundamental concept of tensors using TensorFlow

More specifically,we're going to cover :
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python functions)
* Using  GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!




## Introduction to Tensors


In [1]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.18.0


In [ ]:
x=tf.constant(7)
x


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
x.ndim

0

In [ ]:
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled.ndim

2

In [ ]:
#Create two random (but the same) tensors

random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(42)


In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
import numpy as np


In [ ]:
numpy_a=np.arange(1,25,dtype=np.int32)


In [ ]:
A=tf.constant(numpy_a,shape=(3,8))
B=tf.constant(numpy_a)
A,B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

**Indexing** **Tensor**


In [ ]:
some_list=[1,2,3,4]
some_list[:2]


[1, 2]

In [ ]:
#Create a rank a tensor(4 dimension)

rank_4_tensor=tf.zeros(shape=[2,3,4,5])
#rank_4_tensor=tf.zeros(shape=[4,4,4,4])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:2,:2,:2,:2]
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape


TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [ ]:
#Create a rank_2 tensor(2 dimension)

rank_2_tensor=tf.constant([[10,7],[3,4]])


In [ ]:
rank_2_tensor.ndim

2

In [ ]:
rank_2_tensor[:-1]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

Matrix Multiplication



In [ ]:
tensor=tf.constant([[10,8],
                    [8,5],
                    ])


In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 8,  5]], dtype=int32)>

In [ ]:
tf.matmul(tensor ,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[164, 120],
       [120,  89]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[164, 120],
       [120,  89]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  8],
       [ 8,  5]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[164, 120],
       [120,  89]], dtype=int32)>

In [ ]:
#Matrix multilplication with python operation "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[164, 120],
       [120,  89]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
#Create a tensor(3,2)tensor

x=tf.constant([[1,2],[3,4],[5,6]])

#Create another (3,2) tensor

y=tf.constant([[7,8],[9,10],[11,12]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
x.ndim

2

In [ ]:
x+y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 8, 10],
       [12, 14],
       [16, 18]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tf.reshape(y,shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Try to matrix multiply x by reshaped

x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x=tf.constant([[1,2],[3,4],[5,6]])

y=tf.constant([[7,8],[9,10],[11,12]])

In [ ]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x.shape

TensorShape([3, 2])

In [ ]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(x,tf.reshape(y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
#Create a random tensor with values between 0 and 100 of size 50


E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41, 69,  8, 38, 75, 16, 27, 91, 64, 64, 46, 78, 14, 83, 29,  2, 99,
       23,  9, 23,  2, 14, 99,  7, 56, 95,  3, 50, 29, 64, 93, 66, 60, 51,
       26, 22, 92, 65, 33, 74, 31, 41, 34, 47, 32, 10, 74, 88, 41, 99])>

In [ ]:
E=tf.constant(np.random.randint(0,100,size=50))

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([12, 60,  7, 77, 19, 44,  6, 12, 39, 13, 87, 22, 95, 98, 76, 90,  6,
       10, 29, 21, 24, 53, 92, 90, 78,  6, 50, 14, 55, 97, 96, 42, 29, 12,
       14, 91, 77, 67,  2, 29,  0, 67, 71, 74, 92, 80, 57, 40, 75, 10])>

In [ ]:
Eg=tf.constant(np.random.randint(0,100,size=10))
Eg

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([40, 90, 53, 47, 56, 72, 17, 90, 29, 47])>

In [ ]:
# Find the minimum

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the maxmin

tf.reduce_max(ten)

<tf.Tensor: shape=(), dtype=int32, numpy=45>

In [ ]:
# Find the mean

tf.reduce_mean(ten)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [ ]:
tensor=tf.constant([[10,8],[1,6]])


In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[108, 128],
       [ 16,  44]], dtype=int32)>

In [ ]:
x=tf.constant([[1,2],[3,4],[5,6]])

y=tf.constant([[7,8],[9,10],[11,12]])



In [ ]:
x * y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

In [ ]:
#let's change the shape of y

tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Let's change the shape of y


tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
#Let's change shape of x


tf.reshape(x,shape=(2,3))



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
import numpy as np

In [ ]:
x @ tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
x_reshape=tf.reshape(x,(2,3))

x_reshape

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
x_res=tf.reshape(x,(2,3))

In [ ]:
x_res


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
x @ tf.reshape(y,(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
tf.reshape(x,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
#Perform the dotproduct on x and y

tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [3]:
#Perform matrix multiplication between x and y (reshape)


tf_res=tf.reshape(x,(2,3))

tf_res


NameError: name 'x' is not defined

In [2]:
tf_res.shape

NameError: name 'tf_res' is not defined

In [8]:
import tensorflow as tf

In [9]:
import numpy as np

In [11]:
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([15, 38, 21,  8, 71, 92, 95, 99, 57, 58, 49, 44, 90, 54,  5, 21, 31,
       41, 93, 83, 99, 61, 58, 13, 98,  9,  1, 34, 38, 58, 78,  5,  1, 58,
       62, 88, 88, 92, 21, 43, 31, 55, 73,  6, 14, 50, 82,  3, 71, 73])>